on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04

    name: Go build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build